---
name: Check building the docker image and possibly push

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 1 * * 0" # every sunday at 1 am

env:
  IMAGE_NAME: srb2kart

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
      - name: Buildah Build
        id: build-image
        uses: redhat-actions/buildah-build@v2.13
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest 1 1.6 1.6.${{ github.sha }}
          archs: amd64, arm64
          containerfiles: |
            ./Dockerfile
      - name: Push to Quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/aliciabytes
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Push to Docker Hub
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  update-description:
    needs: [container]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: alicianibbles/srb2kart
          short-description: ${{ github.event.repository.description }}
